version: '3'

services:
  postgresql:
    image: postgres
    ports:
      - '5556:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: admin
    networks:
      - network-estagio

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-back
    ports:
      - 3000:3333
    volumes:
      - .:/home/node/app
    networks:
      - network-estagio
    depends_on:
      - postgresql

networks:
  network-estagio:
    driver: bridge
